version: '3'

services:
  php:
    build: ./php
    container_name: web
    volumes:
      - ../cruiser:/var/www/cruiser
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 80:80
  node:
    build: ./node
    container_name: node
    tty: true
    volumes:
      - ../cruiser/:/usr/src/app
